# True/False if you want to back up sales/.d1c files
backup_sales: True

# If backup_sales is set to True, this is where the .d1c files will be saved
# This folder will be the root, and .d1c files will be in 
# ./SITENUMBER/YYMMDD 
# ex: ./001488/180822
backup_folder: "./"

# What will be included in the PT file name
file_name:
  # Allows for custom file name beginning if wanted
  custom: 
    custom_beginning: True
    text: "pt"
  siteid: True
  date:
    include: True
    # True = yymmdd
    # False = mmddyy
    format: False
    # Adds day to date. Only used on Anaheim Truck Depot sites
    add_day: True
  extension: ".dat"
  
# Folders to look in for .d1c files. Add more underneath with
# -"Path goes here"
# YOU MUST USE DOUBLE BACKSLASHES
# EX: "C:\\ICS\\YOUR FOLDER HERE\\ANOTHER FOLDER"
input_folders:
  - "C:\\ICS\\ptGen\\001488\\180711\\d1c files"

# Path where PT file will get output
# MUST USE DOUBLE BACKSLASHES
# EX: "C:\\ICS\\YOUR FOLDER HERE\\ANOTHER FOLDER"
output_folder: "C:\\Users\\zane.pollard.THESITECONTROLL\\Desktop"

# value that dictates whether a pump total file will 
# need to be moved along with the PT file.
# Used when processing Anaheim sites
pump_total: False